export enum ColorScheme {
  Blue = 'blue',
  BlackAlpha = 'blackAlpha',
  WhiteAlpha = 'whiteAlpha',
  Gray = 'gray',
  Red = 'red',
  Orange = 'orange',
  Yellow = 'yellow',
  Green = 'green',
  Teal = 'teal',
  Cyan = 'cyan',
  Purple = 'purple',
  Pink = 'pink',
  LinkedIn = 'linkedin',
  Facebook = 'facebook',
  Messenger = 'messenger',
  Whatsapp = 'whatsapp',
  Twitter = 'twitter',
  Telegram = 'telegram'
}
